# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ETtodayAssignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ETtodayAssignment
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'SnapKit', '~> 5.6.0'

  target 'ETtodayAssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
end